version: '3.1'

services:
  app_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/mysql:/docker-entrypoint-initdb.d
      - ./config/my.cnf:/etc/mysql/my.cnf
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
